#!/bin/bash
####################################################################
# Script name: countPreProc	
# Description: calculates the numbers of lines the preprocessor is adding
# Parameters: (1) directory name
# Return value: the amout of lines the preprocessor adds to a .c code
####################################################################

if (( $# == 1 )); then #checks if a parameter have been recived
counter=0
for i in $(find ./"$1" -maxdepth 1 -type f -name '*.c'); do # Whitespace-safe but not recursive.
    counter=$((gcc -E "$i") | wc -l)-$((cat "$i") | wc -l)+$((counter))
done
   echo $((counter)) 


else
	echo theres a problem with the parameters
	exit 2
fi





